name: fluttershare
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  timeago: ^2.0.29
  cloud_firestore: ^0.14.4
  firebase_core: "^0.5.3"
  firebase_storage: ^5.2.0
  firebase_auth: ^0.18.4+1
  google_sign_in: "^4.5.6"
  #flutter_facebook_auth: "^0.3.0"
  cupertino_icons: ^1.0.0
  firebase_messaging: ^7.0.3
  rflutter_alert: ^1.0.3
  provider: ^3.0.0
  http: ^0.12.1
  flutter_barcode_scanner: ^1.0.1
  flushbar: ^1.10.4
  firebase_database: ^4.4.0
  path_provider: ^1.6.24
  flutter_launcher_icons: ^0.8.1  # See flutter_icons: # cmd only: flutter pub get; flutter pub run flutter_launcher_icons:main;
  dependency_validator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  image_path: "assets/images/ekonobar.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/ekonobar.png
    - assets/images/login.png
    - assets/images/draver.png
    - assets/images/qrcode.png
    - assets/images/pozadina.png
    - assets/images/google_signin_button.png
    - assets/images/email_signin_button.png
    - assets/images/upload.svg
    - assets/images/search.svg
    - assets/images/activity_feed.svg
    - assets/images/no_content.svg
    - assets/images/google-logo.png
    - assets/images/facebook-logo.png
    - assets/images/email-logo.png
    